var i18nstrings =
{'de':
{
    'title': 'Titel',
    'subtitle': 'Untertitel',
    'channel': 'Kanal',
    'channels': 'Kanäle',
    'allChannels': 'Alle Kanäle',
    'search': 'Suchen',
    'priority': 'Priorität',
    'start': 'Start',
    'end': 'Ende',
    'config': 'Konfig.',
    'duration': 'Dauer',
    'status': 'Status',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'description': 'Beschreibung',
    'genre': 'Genre',
    'record': 'Aufnehmen',
    'errorCreatingOrDeleteRecordingEntry': 'Fehler beim Erstellen/Löschen der Aufnahme',
    'recordingEntryNotFound': 'Aufnahme nicht gefunden',
    'errorCancellingEntry': 'Fehler beim Abbrechen der Aufnahme',
    'errorDeletingEntry': 'Fehler beim Löschen der Aufnahme',
    'reallyDeleteItem': 'Möchten Sie diesen Eintrag wirklich löschen?',
    'active': 'aktiv',
    'inactive': 'inaktiv',
    'enabled': 'Aktiviert',
    'yes': 'Ja',
    'no': 'Nein',
    'tags': 'Tags',
    'tag': 'Tag',
    'createdBy': 'Erstellt von',
    'comment': 'Kommentar',
    'loading': 'Lade...',
    'monday': 'Montag',
    'monday.short': 'Mo',
    'tuesday': 'Dienstag',
    'tuesday.short': 'Di',
    'wednesday': 'Mittwoch',
    'wednesday.short': 'Mi',
    'thursday': 'Donnerstag',
    'thursday.short': 'Do',
    'friday': 'Freitag',
    'friday.short': 'Fr',
    'saturday': 'Samstag',
    'saturday.short': 'Sa',
    'sunday': 'Sonntag',
    'sunday.short': 'So',
    'upcomingRecordings': 'Kommende Aufnahmen',
    'finishedRecordings': 'Beendete Aufnahmen',
    'failedRecordings': 'Fehlerhafte Aufnahmen',
    'digitalVideoRecorder': 'Digitaler Videorekorder',
    'automaticRecorder': 'Auto-Aufnahme',
    'informationStatus': 'Informationen/Status',
    'electronicProgramGuide': 'Elektronischer Programmführer',
    'about': 'Über',
    'startingAround': 'Start (ca.)',
    'dateFormat': 'dd.MM.yyyy',
    'getMore': 'mehr...',
    'prio.important': 'Wichtig',
    'prio.high': 'Hoch',
    'prio.normal': 'Normal',
    'prio.low': 'Niedrig',
    'prio.unimportant': 'Unwichtig',
    'prio.notset': 'Nicht gesetzt',
    'newEntry': 'Neuer Eintrag...',
    'subscriptions': 'Verbindungen',
    'adapters': 'Adapter',
    'any': '(egal)',
    'hostname': 'Hostname',
    'name': 'Name',
    'path': 'Pfad',
    'devicename': 'Gerätename',
    'deliverysystem':'System',
    'services':'Services',
    'muxes':'Muxes',
    'signal':'Signal',
    'reload':'Neu laden',
    'desktopSite':'Desktop-Version',
    'episode': 'Episode',
    'status.undefined': '',
    'status.recording': 'Aufnahme läuft',
    'status.scheduled': 'Aufnahme geplant',
    'status.recordingError': 'Fehler bei Aufnahme',
    'status.Scheduled for recording': 'Aufnahme geplant',
    'status.Waiting for stream': 'Warten auf Stream',
    'status.Waiting for program start': 'Warten auf Programmstart',
    'status.Running': 'Läuft',
    'status.Commercial break': 'Werbepause',
    'status.Invalid': 'Ungültig',
    'status.File Missing': 'Datei fehlt',
    'status.Completed OK': 'Korrekt beendet',
    'status.Time missed': 'Zeit verpasst',
    'hour.short': ' Std.',
    'liveTv': 'Live-TV',
    'timeline': 'Zeitleiste',
    'imdbSearch': 'IMDB-Suche',
    'tmdbSearch': 'TMDB-Suche',
    'diskspace': 'Speicherplatz',
    'magazine': 'Programmzeitschrift',
    'backToMobileUi': 'zurück zur mobilen Ansicht',
    'mobileUi': 'mobile Ansicht',
    'minDuration': 'Min. Dauer',
    'maxDuration': 'Max. Dauer'
},
'en':
{
    'title': 'Title/Search',
    'subtitle': 'Subtitle',
    'channel': 'Channel',
    'channels': 'Channels',
    'allChannels': 'All channels',
    'search': 'Search',
    'priority': 'Priority',
    'start': 'Start',
    'end': 'End',
    'config': 'Config.',
    'duration': 'Duration',
    'status': 'Status',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'description': 'Description',
    'genre': 'Genre',
    'record': 'Record',
    'errorCreatingOrDeleteRecordingEntry': 'Error creating or delete recording entry',
    'recordingEntryNotFound': 'Recording entry not found',
    'errorCancellingEntry': 'Error cancelling entry',
    'errorDeletingEntry': 'Error deleting entry',
    'reallyDeleteItem': 'Do you really want to delete this item?',
    'active': 'active',
    'inactive': 'inactive',
    'enabled': 'Enabled',
    'yes': 'Yes',
    'no': 'No',
    'tags': 'Tags',
    'tag': 'Tag',
    'createdBy': 'Created by',
    'comment': 'Comment',
    'directory': 'Directory',
    'duplicate': 'Duplicate',
    'uiid': 'Uiid',
    'errors': 'Errors',
    'filesize': 'Filesize',
    'loading': 'Loading...',
    'monday': 'Monday',
    'monday.short': 'Mon',
    'tuesday': 'Tuesday',
    'tuesday.short': 'Tue',
    'wednesday': 'Wednesday',
    'wednesday.short': 'Wed',
    'thursday': 'Thursday',
    'thursday.short': 'Thu',
    'friday': 'Friday',
    'friday.short': 'Fri',
    'saturday': 'Saturday',
    'saturday.short': 'Sat',
    'sunday': 'Sunday',
    'sunday.short': 'Sun',
    'upcomingRecordings': 'Upcoming recordings',
    'finishedRecordings': 'Finished recordings',
    'failedRecordings': 'Failed recordings',
    'digitalVideoRecorder': 'Digital video recorder',
    'automaticRecorder': 'Automatic recorder',
    'informationStatus': 'Information/Status',
    'electronicProgramGuide': 'Electronic program guide',
    'about': 'About',
    'startingAround': 'Start (ca.)',
    'dateFormat': 'yyyy-MM-dd',
    'getMore': 'more...',
    'prio.important': 'Important',
    'prio.high': 'High',
    'prio.normal': 'Normal',
    'prio.low': 'Low',
    'prio.unimportant': 'Unimportant',
    'prio.notset': 'Not set',
    'newEntry': 'New entry...',
    'subscriptions': 'Subscriptions',
    'adapters': 'Adapters',
    'any': '(any)',
    'hostname': 'Hostname',
    'name': 'Name',
    'path': 'Path',
    'devicename': 'Device name',
    'deliverysystem':'System',
    'services':'Services',
    'muxes':'Muxes',
    'signal':'Signal',
    'reload':'Reload',
    'desktopSite':'Desktop-Site',
    'episode': 'Episode',
    'status.undefined': '',
    'hour.short': 'h',
    'liveTv': 'Live-TV',
    'timeline': 'Timeline',
    'imdbSearch': 'Search IMDB',
    'imdbSearchMobile': 'Search IMDB Mobile',
    'tmdbSearch': 'Search TMDB',
    'tmdbAttribution': 'This product uses the <a href="http://themoviedb.org/" target="_blank">TMDb</a> API but is not endorsed or certified by TMDb.',
    'diskspace': 'Disk space',
    'magazine': 'Listings',
    'backToMobileUi': 'back to mobile UI',
    'mobileUi': 'mobile UI',
    'minDuration': 'min. duration',
    'maxDuration': 'max. duration',
    'recorddup': 'Duplicate',
    'record.Record all': 'Record all', 
    'record.All: Record if different episode number': 'All: Record if different episode number',
    'record.All: Record if different subtitle': 'All: Record if different subtitle',
    'record.All: Record if different description': 'All: Record if different description',
    'record.All: Record once per week': 'All: Record once per week',
    'record.All: Record once per day': 'All: Record once per day',
    'record.Local: Record if different episode number': 'Local: Record if different episode number',
    'record.Local: Record if different title': 'Local: Record if different title',
    'record.Local: Record if different subtitle': 'Local: Record if different subtitle',
    'record.Local: Record if different description': 'Local: Record if different description',
    'record.Local: Record once per week': 'Local: Record once per week',
    'record.Local: Record once per day': 'Local: Record once per day',
    'fulltext': 'Full-text',
    'autorec': 'Autorec',
    'filename': 'Filename'
},
'sv':
{
    'title': 'Titel/Sök',
    'subtitle': 'Undertext',
    'channel': 'Kanal',
    'channels': 'Kanaler',
    'allChannels': 'Alla kanaler',
    'search': 'Sök',
    'priority': 'Prioritet',
    'start': 'Start',
    'end': 'Slut',
    'config': 'Konfig',
    'duration': 'Längd',
    'status': 'Status',
    'save': 'Spara',
    'cancel': 'Avbryt',
    'delete': 'Radera',
    'description': 'Beskrivning',
    'genre': 'Genre',
    'record': 'Spela in',
    'errorCreatingOrDeleteRecordingEntry': 'Det gick inte att skapa eller ta bort inspelningspost',
    'recordingEntryNotFound': 'Inspelningsinmatning hittades inte',
    'errorCancellingEntry': 'Fel vid inställning av inmatning',
    'errorDeletingEntry': 'Ett fel uppstod vid radering av posten',
    'reallyDeleteItem': 'Vill du verkligen radera denna post?',
    'active': 'Aktiv',
    'inactive': 'Inaktiv',
    'enabled': 'Aktiverad',
    'yes': 'Ja',
    'no': 'Nej',
    'tags': 'Taggar',
    'tag': 'Taggar',
    'createdBy': 'Skapad av',
    'comment': 'Kommentar',
    'directory': 'Katalog',
    'duplicate': 'Duplicerad',
    'uiid': 'Uiid',
    'errors': 'Fel',
    'filesize': 'Filstorlek',
    'loading': 'Laddar...',
    'monday': 'Måndag',
    'monday.short': 'Mån',
    'tuesday': 'Tisdag',
    'tuesday.short': 'Tis',
    'wednesday': 'Onsdag',
    'wednesday.short': 'Ons',
    'thursday': 'Torsdag',
    'thursday.short': 'Tor',
    'friday': 'Fredag',
    'friday.short': 'Fre',
    'saturday': 'Lördag',
    'saturday.short': 'Lör',
    'sunday': 'Söndag',
    'sunday.short': 'Sön',
    'upcomingRecordings': 'Kommande inspelningar',
    'finishedRecordings': 'Avslutade inspelningar',
    'failedRecordings': 'Felaktiga inspelningar',
    'digitalVideoRecorder': 'Digital mediaspelare',
    'automaticRecorder': 'Automatisk inspelare',
    'informationStatus': 'Information/Status',
    'electronicProgramGuide': 'Elektronisk programguide',
    'about': 'Om',
    'startingAround': 'Startar (ca.)',
    'dateFormat': 'yyyy-MM-dd',
    'getMore': 'mera...',
    'prio.important': 'Viktig',
    'prio.high': 'Hög',
    'prio.normal': 'Normal',
    'prio.low': 'Låg',
    'prio.unimportant': 'Oviktig',
    'prio.notset': 'Inte inställd',
    'newEntry': 'Ny post...',
    'subscriptions': 'Anslutningar',
    'adapters': 'Adaptrar',
    'any': '(Någon)',
    'hostname': 'Värdnamn',
    'name': 'Namn',
    'path': 'Sökväg',
    'devicename': 'Enhetsnamn',
    'deliverysystem':'System',
    'services':'Tjänster',
    'muxes':'Muxar',
    'signal':'Signal',
    'reload':'Ladda om',
    'desktopSite':'Skrivbordssida',
    'episode': 'Episod',
    'status.undefined': '',
    'hour.short': ' t',
    'liveTv': 'Lajv-TV',
    'timeline': 'Tidslinje',
    'imdbSearch': 'Sök IMDB',
    'imdbSearchMobile': 'Sök IMDB Mobil',
    'tmdbSearch': 'Sök TMDB',
    'tmdbAttribution': 'This product uses the <a href="http://themoviedb.org/" target="_blank">TMDb</a> API but is not endorsed or certified by TMDb.',
    'diskspace': 'Disk utrymme',
    'magazine': 'Boktablå',
    'backToMobileUi': 'Tillbaka till mobilgränssnittet',
    'mobileUi': 'Mobilgränssnittet',
    'minDuration': 'Min längd',
    'maxDuration': 'Max längd',
    'recorddup': 'Duplicera',
    'record.Record all': 'Spela in alla', 
    'record.All: Record if different episode number': 'Alla: Spela in om olika episodnummer',
    'record.All: Record if different subtitle': 'Alla: Spela in om olika undertexter',
    'record.All: Record if different description': 'Alla: Spela in om annan beskrivning',
    'record.All: Record once per week': 'Alla: Spela in en gång i veckan',
    'record.All: Record once per day': 'Alla: Spela in en gång per dag',
    'record.Local: Record if different episode number': 'Lokal: Spela in om olika episodnummer',
    'record.Local: Record if different title': 'Lokal: Spela in om en annan titel',
    'record.Local: Record if different subtitle': 'Lokal: Spela in om olika undertexter',
    'record.Local: Record if different description': 'Lokal: Spela in om annan beskrivning',
    'record.Local: Record once per week': 'Lokal: Spela in en gång i veckan',
    'record.Local: Record once per day': 'Lokal: Spela in en gång per dag',
    'fulltext': 'Sök i all text',
    'autorec': 'Autoinspel.',
    'filename': 'Filnamn',
    'inputs': 'Ingångar'
}
};
